# Generated by Django 3.2 on 2021-11-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='uv',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
