# Generated by Django 3.2.9 on 2021-11-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_name',
            new_name='created_time',
        ),
    ]
