# Generated by Django 3.2.9 on 2021-11-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_created_name_post_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owenr',
            new_name='owner',
        ),
    ]
