# Generated by Django 3.2 on 2021-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211111_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='ppp', to='blog.Category', verbose_name='分类'),
        ),
    ]
