# Generated by Django 3.2.9 on 2021-11-24 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211124_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categoryss',
        ),
        migrations.RemoveField(
            model_name='question',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
